role: "server" #

ip: "127.0.0.1" #

port: 9000 #

n_clients: 3 #

model: "SimpleCNN" #

data: "MNIST" #

batch_size: 64 #

path: "./datasets" #

alpha: 100 #

global_epoch: 10 #

algorithm: "FedAVG" #

device: "cpu" #